run:
  timeout: 5m
  tests: false

output:
  format: tab

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

linters:
  enable:
    - govet
    - revive

    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck

    - exhaustive
    - gofmt
    - whitespace
    - goimports
  disable-all: true
  fast: false
