{
 "title": "NeoFS Network Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "net",
    "label": "Network",
    "query": {
     "query": "label_values(neofs_net_monitor_epoch,net)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage nodes side chain GAS balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_sn_balance{net=\"$net\"}/100000000",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Alphabet mainnet GAS balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_alphabet_balance{net=\"$net\"}/100000000",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Network epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neofs_net_monitor_epoch{net=\"$net\"}"
    }
   ]
  },
  {
   "title": "Storage nodes side chain Notary balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_sn_balance_notary{net=\"$net\"}/100000000",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Alphabet side chain Notary balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_alphabet_balance_notary{net=\"$net\"}/100000000",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Amount of dropped nodes in the next epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neofs_net_monitor_netmap_dropped{net=\"$net\"}"
    }
   ]
  },
  {
   "title": "Amount of new nodes in the next epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neofs_net_monitor_netmap_new{net=\"$net\"}"
    }
   ]
  },
  {
   "title": "Proxy contract GAS balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_proxy_balance{net=\"$net\"}/100000000",
     "legendFormat": "ProxyContract"
    }
   ]
  },
  {
   "title": "Inner ring side chain GAS balances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_net_monitor_ir_balance{net=\"$net\"}/100000000",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Asset supply",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "neofs_net_monitor_main_chain_supply/1e8",
     "legendFormat": "Main chain supply"
    },
    {
     "expr": "neofs_net_monitor_side_chain_supply/1e12",
     "legendFormat": "Side chain supply"
    },
    {
     "expr": "abs(neofs_net_monitor_main_chain_supply*1e4 - neofs_net_monitor_side_chain_supply)/1e12",
     "legendFormat": "delta"
    }
   ]
  },
  {
   "title": "Storage node map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 24 },
   "valueName": "current",
   "targets": [
    {
     "expr": "neofs_net_monitor_netmap{net=\"$net\"}"
    }
   ]
  }
 ]
}