version: '2.4'

services:
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    networks:
      - internet
    restart: on-failure


  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: [
        '--config.file=/etc/prometheus/prometheus.yml',
    ]
    ports:
      - 9090:9090
    networks:
      - internet
    restart: on-failure

  neofs-net-monitor:
    image: neofs-net-monitor:0.1.0
    container_name: neofs-net-monitor
    depends_on:
      - prometheus
    environment:
      - NEOFS_NET_MONITOR_CONTRACTS_NETMAP=15105c7bbae4cfed65cbe2d5ddb26939d022e8a4
      - NEOFS_NET_MONITOR_CONTRACTS_PROXY=dcc891f08c8126ac2910bad3fe50678a70d9cb82
      - NEOFS_NET_MONITOR_RPC_ENDPOINT=http://192.168.130.90:30333
      - NEOFS_NET_MONITOR_METRICS_INTERVAL=15s
    networks:
      - internet
    restart: on-failure

networks:
  internet:
    external:
      name: basenet_internet
