version: '2.4'

networks:
  monitor-net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    networks:
      - monitor-net
    restart: on-failure

  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: [
        '--config.file=/etc/prometheus/prometheus.yml',
    ]
    networks:
      - monitor-net
    restart: on-failure

  neofs-net-monitor:
    image: nspccdev/neofs-net-monitor:0.3.0
    container_name: neofs-net-monitor
    depends_on:
      - prometheus
    environment:
      - NEOFS_NET_MONITOR_CONTRACTS_NETMAP=5283a843ee68f8fa9ee664df6b495054be5738d4
      - NEOFS_NET_MONITOR_CONTRACTS_PROXY=60cf507792a07854c7c850ba204b3be7a66aa109
      - NEOFS_NET_MONITOR_RPC_ENDPOINT=https://rpc1.morph.fs.neo.org:40341
      - NEOFS_NET_MONITOR_GEOIP_ACCESS_KEY=<ACCESS-TOKEN>
    networks:
      - monitor-net
    restart: on-failure
