version: '2.4'

networks:
  monitor-net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    networks:
      - monitor-net
    restart: on-failure

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: [
        '--config.file=/etc/prometheus/prometheus.yml',
    ]
    networks:
      - monitor-net
    restart: on-failure

  neofs-net-monitor:
    image: nspccdev/neofs-net-monitor:0.9.5
    container_name: neofs-net-monitor
    depends_on:
      - prometheus
    environment:
      - NEOFS_NET_MONITOR_METRICS_INTERVAL=15s
      - NEOFS_NET_MONITOR_LOCODE_DB_PATH=locode/db
      - NEOFS_NET_MONITOR_MAINNET_RPC_ENDPOINT=${NEOFS_NET_MONITOR_MAINNET_RPC_ENDPOINT}
      - NEOFS_NET_MONITOR_MORPH_RPC_ENDPOINT=${NEOFS_NET_MONITOR_MORPH_RPC_ENDPOINT}
      - NEOFS_NET_MONITOR_CONTRACTS_NEOFS=${NEOFS_NET_MONITOR_CONTRACTS_NEOFS}
    volumes:
      - ./../locode/locode_db:/locode/db
    networks:
      - monitor-net
    restart: on-failure
