version: '2.4'

networks:
  monitor-net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    networks:
      - monitor-net
    restart: on-failure


  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: [
        '--config.file=/etc/prometheus/prometheus.yml',
    ]
    networks:
      - monitor-net
    restart: on-failure

  neofs-net-monitor:
    image: neofs-net-monitor:0.1.0
    container_name: neofs-net-monitor
    depends_on:
      - prometheus
    environment:
      - NEOFS_NET_MONITOR_CONTRACTS_NETMAP=7b383bc5a385859469f366b08b04b4fcd9a41f55
      - NEOFS_NET_MONITOR_CONTRACTS_PROXY=82b404558924457e46999475fe04fcf0e371532b
      - NEOFS_NET_MONITOR_RPC_ENDPOINT=http://rpc1-morph.preview4.nspcc.ru:24333
      - NEOFS_NET_MONITOR_GEOIP_ACCESS_KEY=<ACCESS-TOKEN>
    networks:
      - monitor-net
    restart: on-failure