version: '2.4'

networks:
  monitor-net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    networks:
      - monitor-net
    restart: on-failure

  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: [
        '--config.file=/etc/prometheus/prometheus.yml',
    ]
    networks:
      - monitor-net
    restart: on-failure

  neofs-net-monitor:
    image: nspccdev/neofs-net-monitor:0.4.0
    container_name: neofs-net-monitor
    depends_on:
      - prometheus
    environment:
      - NEOFS_NET_MONITOR_CONTRACTS_NETMAP=86f589459b0b0ae47d31f3b9b340d6d431358954
      - NEOFS_NET_MONITOR_MAINNET_RPC_ENDPOINT=https://rpc01.testnet.n3.nspcc.ru:21331
      - NEOFS_NET_MONITOR_MORPH_RPC_ENDPOINT=https://rpc01.morph.testnet.fs.neo.org:51331
      - NEOFS_NET_MONITOR_GEOIP_ACCESS_KEY=<ACCESS-TOKEN>
    networks:
      - monitor-net
    restart: on-failure
